### ISSUE TITLE
Do push code on which you are working or if you have solved any problem in any programming language !!

### ISSUE THREAD

**Issue by hanshulll** [hanshulll/Hacktoberfest2021#1]
**Do push code on which you are working or if you have solved any problem in any programming language !!**

**Comment by RiyaBhandari-2811** [comment]
Hey can I push some java code , if you don't mind merging it ..

**Comment by Swagnik02** [comment]
want to push some java codes for hacktoberfest

**Comment by hanshulll** [comment]
@RiyaBhandari-2811 
**I have merged your PR do check on hactoberfest page and let me know what status does it shows**

**Comment by hanshulll** [comment]
@Swagnik02 
**Yeah sure No problem at all**

**Comment by RiyaBhandari-2811** [comment]
Yes it is merged , Thank you  and yes I've gave you star ⭐

**Comment by krishnavpai** [comment]
Hi there,
Wanted to contribute and learn more.

**Comment by hanshulll** [comment]
@krishnavpai 
**Feel free to contribute and your PR has been merged keep hacking**

**Comment by krishnavpai** [comment]
Thank you

**Comment by priyansh71** [comment]
Hello, I made a PR of an modular algebra theorem code in python with an example in the file itself. can you check if it meets the standards?

**Comment by hanshulll** [comment]
@priyansh71 
**👍🏻**

**Comment by hanshulll** [comment]
@krishnavpai 
**👍🏻**

**Comment by Siddhesh4501** [comment]
can i work on this

**Comment by hanshulll** [comment]
@Siddhesh4501 
**Yeah you can all types of contributions are accepted**

**Comment by abhay-lal** [comment]
Hi can I contribute to this ..

**Comment by hanshulll** [comment]
@abhay-lal 
**Yeah sure why not. Keep hackin**

**Comment by sreyom31** [comment]
Hi, want to contribute to this repo. Can you please assign me ?

**Comment by hanshulll** [comment]
@sreyom31 
**just start a pull request after adding some code file in your prefered language and i will merge it for sure. Keep hacking**

**Comment by sudipbhakat07** [comment]
Hello Hanshull, I have created a pull request, please merge it.
And Thank you in advance!

**Comment by hanshulll** [comment]
@sudipbhakat07
**yeah sure just don't forget to give a star to the repo 😉. Keep hackin**

**Comment by sudipbhakat07** [comment]
> @sudipbhakat07 **yeah sure just don't forget to give a star to the repo 😉. Keep hackin**

Sure....thanks🤘

**Comment by sauravs0** [comment]
Hello Hanshull, I created a pull request to add some DP problems in c++, please merge it under `Hacktoberfest` label. TIA.
I have also starred your repo.

**Comment by Kavs-123** [comment]
Hey @hanshulll !
Would be very happy to contribute to this, can I contribute to the same and work on it?
Thanks

**Comment by hanshulll** [comment]
@sauravs0 
**Wohoo!! Congrats🥳 your PR has been merged.**

**Comment by hanshulll** [comment]
@Kavs-123 
**you can contribute with any code it can be something which you are currently learning or it can be any code problem which you've solved**

**Comment by pranavagrawal321** [comment]
Hello @hanshulll !
I have created a pull request. Please spare some time to merge it

**Comment by hanshulll** [comment]
@pranavagrawal321 
**Your PR has been successfully merged Thank you so much for your valuable contribution. Do give a star to the repo if it helped you and check other repo too for more contributions. Keep hacking**

**Comment by Karssido** [comment]
Hello @hanshulll 
I have created a PR for a Email- Sender in Python. Please merge it if it is good under the tag Hacktoberfest 2021

**Comment by hanshulll** [comment]
@Karssido 
**Wohoo!! Congrats🥳 your PR has been merged. Happy Hactoberfest**

**Comment by Yashika27** [comment]
Hey @hanshulll 
I've created PR #144  and  #151. Please have a look and merge if you find it good.

**Comment by hanshulll** [comment]
@Yashika27 
**Yeah cool i am gonna start merging again in the night. And thank you so much for your contribution**

**Comment by Kavs-123** [comment]
> @Kavs-123 **you can contribute with any code it can be something which you are currently learning or it can be any code problem which you've solved. And don't forget to star the repo**

Hey @hanshulll ,
I worked on the same and have created a pr #163...
Requesting you to please give it a watch and merge it if sounds good :)

**Comment by 0901IT201046** [comment]
Sir, Please view and merge my PR #168 in your repo. Thankyou

**Comment by krishnavpai** [comment]
@hanshulll I have seen many repositories being excluded from the project.
Maybe because of spam

**Comment by Rohit5152** [comment]
Bro can I code for
Generating Power set of Array(all subsets of array)
in c++.
please Assign this to me.

**Comment by hanshulll** [comment]
@krishnavpai 
**so I am gonna stop merging for a while be patient full because I’ve merged around 100+ today. Don’t worry if you all have done a quality PR I am gonna definitely merge them but I am not gonna merge for few hours maybe 48 to be precise but you could raise the PR in the mean time!! Also do PR’s in other repo too. Happy hactoberfest do reach me if want to know about something. And don’t forget to Star the repo.**

**Comment by Rohit5152** [comment]
> @krishnavpai **so I am gonna stop merging for a while be patient full because I’ve merged around 100+ today. Don’t worry if you all have done a quality PR I am gonna definitely merge them but I am not gonna merge for few hours maybe 48 to be precise but you could raise the PR in the mean time!! Also do PR’s in other repo too. Happy hactoberfest do reach me if want to know about something. And don’t forget to Star the repo.**

bro i request a pr of Alllsubset of array pleasse merge  it 
this problem is from leetcode

**Comment by ct-27** [comment]
Hey @hanshulll 
I've created PR #191 and #195. Please have a look and merge if you find it good.

**Comment by hanshulll** [comment]
@ct-27 
**yeah sure**

**Comment by RusJaI** [comment]
hi! made a PR  #199 ..please have a look when you're available! Thanks

**Comment by hanshulll** [comment]
@RusJaI
**Yeah sure, But currently their are a lot PR's will review it as soon as possible so don't worry. Happy Hactoberfest and don't forget to star the repo.**

**Comment by Paimon-food** [comment]
Hey,I know u are trying your best to  reveiw a lot of PR 's ..please do check mine too #153 .Thanks in advance

**Comment by arpitarunkumaar** [comment]
hey, I'm a beginner and have added a binomial.cpp program in the c++ folder. Please check it out

**Comment by arpitarunkumaar** [comment]
can u merge my program (binomial.cpp) @hanshulll

**Comment by MayurJ20** [comment]
I would like to contribute some of my codes.
Please refer them at below PR's
#159 #162

**Comment by Mayurishinde27** [comment]
Hello @hanshulll , i would like to work on this issue.Can you please assign this to me?

**Comment by hanshulll** [comment]
@MayurJ20 
**you can contribute with any code it can be something which you are currently learning or it can be any coding problem that you've solved. And don't forget to star the repo**

**Comment by hanshulll** [comment]
**EVERYONE,** 
**Don't worry your PR's will be approved soon as you may know their are a lot PR's right now and also it's a one month program so don't worry it will be approved as soon as possible also I can't merge all PR's blindly as it may result in the repo being excluded from the program like many other repo so be patient full you PR will be accepted soon. Happy Hactoberfest 🙌🏻**

**Comment by vivekarora-02** [comment]
Hey there, I would like to contribute 
. Can you please assign me this issue? 
 ThankYou!.

**Comment by Shreya119** [comment]
Hey, @hanshulll just contributed to your repo. Please refer to #251 and also gave a star to the repo.

**Comment by hanshulll** [comment]
> Hey there, I would like to contribute
> . Can you please assign me this issue?
> ThankYou!.
@MayurJ20 
**you can contribute with any code it can be something which you are currently learning or it can be any coding problem that you've solved. And don't forget to star the repo**

**Comment by hanshulll** [comment]
> Hey, @hanshulll just contributed to your repo. Please refer to #251 and also gave a star to the repo.

@ Shreya119
**Yeah Sure, will review it soon !!**

**Comment by Udyansingh** [comment]
@hanshulll I have made PR #317 , Please refer it.

**Comment by hanshulll** [comment]
@Udyansingh 
**Yeah Sure, will review it soon !!**

**Comment by Aozora-86** [comment]
I have made PR #321 , please refer it..

**Comment by hanshulll** [comment]
@everyone 
** Actually this repo is now been excluded from hactoberfest I was fearing that it will happen eventually their can be any reason like a lot of spam PR’s so it can’t be help but yeah it’s a one month long program so their is a lot of time to do more PR’s on many different repo’s. So, yeah Happy Hactoberfest**
