### ISSUE TITLE
burst balloon problem

### ISSUE THREAD

**Issue by manisha-4** [hanshulll/Hacktoberfest2021#333]
can you please assign leetcode burst baloon dp problem to me?

You are given n balloons, indexed from 0 to n - 1. Each balloon is painted with a number on it represented by an array nums. You are asked to burst all the balloons.

If you burst the ith balloon, you will get nums[i - 1] * nums[i] * nums[i + 1] coins. If i - 1 or i + 1 goes out of bounds of the array, then treat it as if there is a balloon with a 1 painted on it.

Return the maximum coins you can collect by bursting the balloons wisely.

**Comment by hanshulll** [comment]
@manisha-4 
** Actually this repo is now been excluded from hactoberfest I was fearing that it will happen eventually their can be any reason like a lot of spam PR’s so it can’t be help but yeah it’s a one month long program so their is a lot of time to do more PR’s on many different repo’s. So, yeah Happy Hactoberfest**
